In [2]:
import numpy as np
np.ones((3,5), dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [4]:
import numpy as np
np.zeros(10,dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
import numpy as np
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [6]:
import numpy as np
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [7]:
import numpy as np
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
import numpy as np
np.random.normal(10,4,(3,4))

array([[ 6.84985023, 14.36211294, 12.60662448, 10.50243489],
       [12.56816034,  9.92127813, 15.83296354,  6.3523236 ],
       [ 5.63170566,  7.13794256, 13.11594184, 11.11586216]])

In [9]:
import numpy as np
np.random.randint(0,10,(3,3))

array([[4, 4, 8],
       [3, 4, 4],
       [2, 1, 9]])