In [1]:
import numpy as np
x= np.array([1,2,3,77,8,4,55,9])
np.split(x,[3,5])

[array([1, 2, 3]), array([77,  8]), array([ 4, 55,  9])]

In [2]:
a,b,c=np.split(x,[3,5])

In [3]:
a

array([1, 2, 3])

In [4]:
b

array([77,  8])

In [5]:
c

array([ 4, 55,  9])

In [6]:
#iki boyutlu


In [7]:
m=np.arange(16).reshape(4,4)

In [8]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [16]:
ust,alt=np.vsplit(m,[2])

In [17]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [21]:
sag,sol=np.hsplit(m,[2])

In [22]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [23]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])